version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/var/www/uploads:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --expand --webroot -w /var/www/certbot -d nosmeri.kro.kr -d sus1004.kro.kr -d jep.nosmeri.kro.kr -d www.ty0652.kro.kr -d iot.jbsh.kro.kr -d file.nosmeri.kro.kr --email parkdohyeon622@gmail.com --agree-tos --non-interactive

networks:
  proxy:
    external: true

volumes:
  uploads:
    external: true
